- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: ${ parameters.appName }
    name: deployment-${ parameters.appName }
    namespace: sales-prod
  spec:
    replicas: '${ #toInt( parameters.prodcount ) }'
    selector:
      matchLabels:
        app: ${ parameters.appName }
    template:
      metadata:
        labels:
          app: ${ parameters.appName }
      spec:
        containers:
          - image: 'justinrlee/nginx:${parameters.tag}'
            name: primary
            ports:
              - containerPort: 80
            readinessProbe:
              httpGet:
                path: /
                port: 80
- apiVersion: v1
  kind: Service
  metadata:
    name: service-${ parameters.appName }
    namespace: sales-prod
  spec:
    ports:
      - port: 80
        protocol: TCP
        targetPort: 80
    selector:
      app: ${ parameters.appName }
    type: LoadBalancer
